apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/cluster-install
- github.com/argoproj/argo-events/manifests/cluster-install

patches:
- path: argo-server-secure-false.yaml
