apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.5.8
- github.com/argoproj/argo-events/manifests/cluster-install?ref=v1.9.2

patches:
- path: argo-server-secure-false.yaml
