apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  source:
    repoURL: https://github.com/dpurge/jdp-homelab.git
    path: kubernetes/environments/jdplnx01/argo-workflows
    targetRevision: main
