apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/stable/argo-cd
- argo-cd.yaml
- argo-workflows.yaml
- workflows.yaml

patches:
- path: ingress.yaml