apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
  
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: workflows
  source:
    repoURL: https://github.com/dpurge/jdp-homelab.git
    path: kubernetes/environments/jdplnx01/workflows
    targetRevision: main
