apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/release-2.11/manifests/install.yaml

patches:
- path: argocd-cmd-params-cm.yaml
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ARGOCD_GPG_ENABLED
        value: "false"
  target:
    kind: Deployment
    name: argocd-server
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ARGOCD_GPG_ENABLED
        value: "false"
  target:
    kind: Deployment
    name: argocd-repo-server
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ARGOCD_GPG_ENABLED
        value: "false"
  target:
    kind: StatefulSet
    name: argocd-application-controller
