---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: leader-locking-infra-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: infra-nfs-subdir-external-provisioner
    namespace: infra
roleRef:
  kind: Role
  name: leader-locking-infra-nfs-subdir-external-provisioner
  apiGroup: rbac.authorization.k8s.io