version: '3'

services:
  jdp-jenkins:
    image: dpurge/jdp-jenkins:latest

    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8080:8080"
      - "50000:50000"
    