apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../stable/applications
- project-infrastructure.yaml

patches:
- path: argo-cd.yaml
- path: argo-workflows.yaml