apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: workflows
  name: docker-build
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: image
        value: bitnami/kaniko:1.20.1
      - name: repo
        value: https://github.com/dpurge/jdp-docker.git
      - name: branch
        value: main
  templates:
    - name: main
      steps:
        - - name: jdp-buildenv
            template: jdp-buildenv
    - name: jdp-buildenv
      inputs:
        artifacts:
        - name: source
          path: /workspace/src
          git:
            repo: "{{workflow.parameters.repo}}"
            revision: main
            usernameSecret:
              name: workflow-secrets
              key: github-username
            passwordSecret:
              name: workflow-secrets
              key: github-password
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace/src
        args:
          - --context=/workspace/src/jdp-buildenv
          - --dockerfile /workspace/src/jdp-buildenv/Dockerfile
          - --cache=false            
        volumeMounts:
          - mountPath: /workspace
            name: workspace
  volumeClaimTemplates:
    - name: workspace
      metadata:
        name: workspace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500Mi