apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: workflows
  name: docker-build
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: image
        value: gcr.io/kaniko-project/executor:v1.20.1
      - name: repo
        value: git://github.com/dpurge/jdp-docker.git
      - name: branch
        value: main
  templates:
    - name: main
      dag:
        tasks:
          - name: jdp-buildenv
            template: jdp-buildenv
    - name: jdp-buildenv
      inputs:
      container:
        image: "{{workflow.parameters.image}}"
        args: [
          "--context", "{{workflow.parameters.repo}}",
          "--context-sub-path", "jdp-buildenv",
          "--no-push"
        ]
