apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: workflows
  name: flashcards-build
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: image
        value: dpurge/jdp-buildenv:2023-11-22
      - name: repo
        value: https://github.com/dpurge/jdp-flashcards.git
      - name: branch
        value: main
      - name: output
        value: out
      - name: artifacts
        value: //jdpnas01.home.arpa/AppData/workflows/flashcards
  templates:
    - name: main
      steps:
        - - name: build
            template: build
        - - name: publish
            template: publish
    - name: build
      inputs:
        artifacts:
        - name: argo-source
          path: /workspace/src
          git:
            repo: https://github.com/dpurge/jdp-flashcards.git
            revision: main
            usernameSecret:
              name: workflow-secrets
              key: github-username
            passwordSecret:
              name: workflow-secrets
              key: github-password
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace/src
        args:
          - sh
        source: |
          task build-all
          mv out /workspace/{{workflow.parameters.output}}
          cd ..
          rm -rf src
        volumeMounts:
          - mountPath: /workspace
            name: flashcards
    - name: publish
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace
        args:
          - sh
        source: |
          mkdir /workspace/artifacts
          mount -t cifs -o username=$ARTIFACTS_USERNAME,password=$ARTIFACTS_PASSWORD,rw,nounix,iocharset=utf8,file_mode=0777,dir_mode=0777 {{workflow.parameters.artifacts}} /workspace/artifacts
          mv /workspace/{{workflow.parameters.output}}/*.apkg /workspace/artifacts/
          umount /workspace/artifacts/
          rm -Rf /workspace/{{workflow.parameters.output}}
        env:
          - name: ARTIFACTS_USERNAME
            valueFrom:
              secretKeyRef:
                name: workflow-secrets
                key: samba-username
          - name: ARTIFACTS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: workflow-secrets
                key: samba-password
        volumeMounts:
          - mountPath: /workspace
            name: flashcards
  volumeClaimTemplates:
    - name: flashcards
      metadata:
        name: flashcards
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 400Mi