apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: workflows
  name: flashcards-build
spec:
  entrypoint: main
  #volumes:
  #  - name: workflow-secrets
  #    secret:
  #      secretName: workflow-secrets
  arguments:
    parameters:
      - name: image
        value: dpurge/jdp-buildenv:2023-11-22
      - name: repo
        value: https://github.com/dpurge/jdp-homelab.git
      - name: branch
        value: main
      - name: output
        value: out
  templates:
    - name: main
      steps:
        - - name: checkout
            template: checkout
        - - name: build
            template: build
        - - name: publish
            template: publish
    - name: checkout
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace
        env:
          #- name: GITHUB_USERNAME
          #  valueFrom:
          #    secretKeyRef:
          #      name: workflow-secrets
          #      key: github-username
          #- name: GITHUB_PASSWORD
          #  valueFrom:
          #    secretKeyRef:
          #      name: workflow-secrets
          #      key: github-password
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: workflow-secrets
                key: ssh-private-key
          - name: SSH_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: workflow-secrets
                key: ssh-public-key
        args:
          - sh
        source: |
          #apt-get install -y openssh-client
          #mkdir -m 700 ~/.ssh
          #ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
          #echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          #echo $SSH_PUBLIC_KEY > ~/.ssh/id_rsa.pub
          #cat <<EOF >>~/.ssh/config
          #Host github.com
          #  IdentityFile ~/.ssh/id_rsa
          #  IdentitiesOnly yes
          #  User git
          #EOF
          #chmod  400 ~/.ssh/id_rsa
          #chmod  644 ~/.ssh/id_rsa.pub
          #chmod  400 ~/.ssh/config
          # git clone -c http.extraHeader="Authorization: Bearer \"$TOKEN\"" --depth 1 --single-branch --branch {{workflow.parameters.branch}} {{workflow.parameters.repo}} .
          # git clone {{workflow.parameters.repo}} .
          rm -fr * .*
          git clone --depth 1 --single-branch --branch {{workflow.parameters.branch}} {{workflow.parameters.repo}} .
          ls -la .
        volumeMounts:
          - mountPath: /workspace
            name: flashcards
    - name: build
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace
        args:
          - sh
        source: task build-all
        volumeMounts:
          - mountPath: /workspace
            name: flashcards
    - name: publish
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace
        args:
          - sh
        source: ls -la /workspace/{{workflow.parameters.output}}
        volumeMounts:
          - mountPath: /workspace
            name: flashcards
  volumeClaimTemplates:
    - name: flashcards
      metadata:
        name: flashcards
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 400Mi