apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  namespace: workflows
  name: youtube-download
spec:
  schedule: "0 3 * * *"
  timezone: "Europe/Warsaw"
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 2     # Default 3
  failedJobsHistoryLimit: 1         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: main
  arguments:
    parameters:
      - name: image
        value: dpurge/jdp-buildenv:2024-02-17
      - name: workspace
        value: /var/jdpnas01/AppData/workflows/youtube
  volumes:
    - name: workspace
      hostPath:
        path: "{{workflow.parameters.workspace}}"
        type: Directory
  templates:
    - name: main
      dag:
        tasks:
        - name: download
          template: youtube-download
    - name: youtube-download
      script:
        image: "{{workflow.parameters.image}}"
        workingDir: /workspace
        volumeMounts:
          - mountPath: /workspace
            name: workspace
        args:
          - /bin/bash
        source: |
          set -e

          workspace="/workspace"
          cfg="config.txt"
          
          for i in $(find $workspace -type f -name $cfg)
          do
            pushd $(dirname $i) > /dev/null
            echo "===== $i ====="
            echo yt-dlp --config-location $cfg || true
            popd > /dev/null
          done
