apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../src/prod/applications
# - metal-lb.yaml

# patches:
# - path: argo-cd.yaml
# - path: argo-workflows.yaml
# - path: metal-lb.yaml