apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  namespace: workflows
  name: docker-build
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: executor
        value: gcr.io/kaniko-project/executor:v1.20.1
      - name: repo
        value: git://github.com/dpurge/jdp-docker.git
  templates:
    - name: main
      dag:
        tasks:
        - name: jdp-buildenv
          template: jdp-buildenv
    - name: jdp-buildenv
      inputs:
      container:
        image: "{{workflow.parameters.executor}}"
        args: [
          "--context", "{{workflow.parameters.repo}}",
          "--context-sub-path", "jdp-buildenv",
          "--destination", "registry.home.arpa:5000/jdp-buildenv:{{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}-{{workflow.creationTimestamp.d}}",
          "--destination", "registry.home.arpa:5000/jdp-buildenv:latest",
          "--insecure"
        ]
