---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: workflows
  namespace: argo
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`workflows.home.arpa`)
      services:
        - kind: Service
          name: argo-server
          port: 2746