apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: metallb-system

spec:
  ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  project: default
  source:
    repoURL: 'https://github.com/dpurge/jdp-homelab.git'
    path: kubernetes/environments/jdplnx01/metal-lb
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy: {}